<?xml version="1.0" encoding="utf-8"?><Database Name="VS..Vparis" Class="DatalinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VIETDUNG\SQLEXPRESS;Initial Catalog=VS..Vparis;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="VS__VparisConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Trunggian" Member="Trunggians">
    <Type Name="Trunggian">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Proid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Icolor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="icid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="iuser_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vuserun" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="vuserpwd" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="vfname" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="vlname" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="igender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="dbirthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="vidcard" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="vaddress" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="vphone" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="vemail" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="iregionid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vavatar" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="vavatartitle" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dcreatedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dlastvisited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="vvalidatekey" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="istatus" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="lang" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IDFaceBook_Google" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MNews" Member="MNews">
    <Type Name="MNew">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Menu_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Brief" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Keywords" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Equals" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ImagesSmall" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Url_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Search" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Orders" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Views" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Lang" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Types" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="TangName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HistoryLogin" Member="HistoryLogins">
    <Type Name="HistoryLogin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameIP" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Creadate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Parent_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="capp" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Url_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Styleshow" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Equals" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Views" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Orders" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="News" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="page_Home" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Titleseo" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Meta" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Keyword" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Check_01" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_02" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_03" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_04" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_05" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Noidung1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung2" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung3" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung4" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung5" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Module" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TangName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.products" Member="products">
    <Type Name="product">
      <Column Name="ipid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="icid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Hang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sanxuat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Brief" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="search" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Images" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImagesSmall" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Equals" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OldPrice" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chekdata" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modified_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Views" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lang" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="News" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Home" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_01" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_02" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_03" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_04" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Check_05" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Titleseo" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Meta" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Keyword" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Anh" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung1" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung2" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung3" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung4" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Noidung5" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TangName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RateCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RateSum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuRutTien" Member="LichSuRutTiens">
    <Type Name="LichSuRutTien">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDThanhVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTienTrongVi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoTienCanRut" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoCoin" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TenNganHang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoTaiKHoan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ChiNhanh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NoiDungChuyenTien" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GhiChu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayDuyet" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NguoiDuyet" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Setting" Member="CauHinhs">
    <Type Name="CauHinh">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Properties" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Lang" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuTuVong" Member="ThuTuVongs">
    <Type Name="ThuTuVong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDThanhVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThuTuSet" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoiNhuanMuaBan" Member="LoiNhuanMuaBans">
    <Type Name="LoiNhuanMuaBan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDThanhVienMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDDonHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongTien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TongTienCon" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TongTienDaChia" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MTreeIDThanhVienMua" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CartDetail" Member="LCartDetails">
    <Type Name="LCartDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Cart" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ipid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Money" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Mausac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Kichco" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienLoiNhuan" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdminUser" Member="LAdminUsers">
    <Type Name="LAdminUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VUSER_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VUSER_PWD" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="VROLE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IASSIGN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DASSIGN_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ILOCKED" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaHong" Member="HoaHongs">
    <Type Name="HoaHong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KieuHoaHong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KieuHH" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TienDonHang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoTienDuocHuong" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PhanTram" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDThanhVienMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDThanhVienHuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDDonHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Carts" Member="LCarts">
    <Type Name="LCart">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Money" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lang" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Phuongthucthanhtoan" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Hinhthucvanchuyen" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StatusGiaoDich" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="IDThanhVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienLoiNhuan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TrangThaiChienLuocVaThongThuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViVipMuaHang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ViChinhMuaHang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CapDiemThanhVien" Member="CapDiemThanhViens">
    <Type Name="CapDiemThanhVien">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDNguoiCap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDNguoiNhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayCap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KieuVi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CongTRu" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuQuyDoiSoCoPhan" Member="LichSuQuyDoiSoCoPhans">
    <Type Name="LichSuQuyDoiSoCoPhan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDThanhVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayCap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KieuVi" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Members" Member="Members">
    <Type Name="Member">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PasWord" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="AnhDaiDien" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lang" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="GioiThieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MTRee" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TienHoaHong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoNguPhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThaiMuaHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTrucTiep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTienDaRut" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TrangThaiMuaHangDatTongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapBac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDLuuTam" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CoPhan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TongTienDaMuaHang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="F1MuaHangDeTinhThuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThaiF1MuaHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViVip" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ViVipDaMuaHang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ViCoPhanSo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="F1MuaHangThuongSoCoPhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThaiF1MuaHangSoCoPhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.S_Trunggian_Delete" Method="S_Trunggian_Delete">
    <Parameter Name="Proid" Parameter="proid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TongThanhVienBenDuoi" Method="TongThanhVienBenDuoi">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="TongThanhVienBenDuoiResult">
      <Column Name="COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.[S-Members_List_TongThanhVien_Tree]" Method="S_Members_List_TongThanhVien_Tree">
    <Parameter Name="IDMember" Parameter="iDMember" Type="System.Int32" DbType="Int" />
    <ElementType Name="S_Members_List_TongThanhVien_TreeResult">
      <Column Name="Tong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TongThanhVienBenDuoi_kichhoat" Method="TongThanhVienBenDuoi_kichhoat">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="TongThanhVienBenDuoi_kichhoatResult">
      <Column Name="COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>